### ISSUE TITLE
Indefinite waiting after failed authentication

### ISSUE THREAD

**Issue by lemmerelassal** [laurentheirendt/devTools#31] opened 2017-03-06 09:21 UTC
Hi Laurent,

Here's a problem I've encountered:

dev>  Your Github username is: lemmerelassal.  (Success) 
dev>  Your Github email is: lemmer.elassal@me.com.  (Success) 
Username for 'https://github.com': L^Hlemmerelassal
Password for 'https://lemmerelassal@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/lemmerelassal/cobratoolbox.git/'

It doesn't change status.

Regards,
Lemmer

**Comment by laurentheirendt** [comment] 2017-03-06 09:28
Try running 
```
>> resetDevTools
```
Then, you can try to re-run `contribute`.

**Comment by laurentheirendt** [comment] 2017-03-06 09:54
May you also try running `contribute(true)` and let me know of the output?

**Comment by laurentheirendt** [comment] 2017-03-06 14:48
Cannot reproduce - closing for now.

**Closed by laurentheirendt** 2017-03-06 14:48 UTC
Labels: needs reproduction
